blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

appname = BlogConfig.name

urlpatterns = [
   path ('blog/', cache_page(60)(BlogListView.as_view()),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
   path('delete_blog/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.urls import path

from newsapp.apps import NewsappConfig
from newsapp.views import NewsLetterListView, NewsLetterDetailView, change_status, ClientListView, MessageListView, \
    ClientUpdateView, MessageUpdateView, ClientCreateView, NewsLetterCreateView, MessageCreateView, \
    NewsLetterUpdateView, MessageDeleteView, NewsLetterDeleteView, ClientDeleteView, mainpage

app_name = NewsappConfig.name

urlpatterns = [
    path('', mainpage, name='home'),
    path('newsletter_list', NewsLetterListView.as_view(), name='newsletter_list'),
    path('newsletter_view/<int:pk>', NewsLetterDetailView.as_view(), name='newsletter_view'),
    path('newsletter_edit/<int:pk>', NewsLetterUpdateView.as_view(), name='newsletter_edit'),
    path('newsletter_delete/<int:pk>', NewsLetterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletter_new/', NewsLetterCreateView.as_view(), name='newsletter_new'),
    path('status/<int:pk>', change_status, name='status'),
    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client_new/', ClientCreateView.as_view(), name='client_new'),
    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message_edit/<int:pk>', MessageUpdateView.as_view(), name='message_edit'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message_new/', MessageCreateView.as_view(), name='message_new'),

]

newsapp/models.py
from django.db import models
from django.template.defaultfilters import truncatechars
from django_apscheduler.models import DjangoJobExecution

from users.models import User

NULLABLE = {'null':True, 'blank':True}

class Client(models.Model):
    first_name = models.CharField(max_length=50, verbose_name ='Имя')
    last_name = models.CharField(max_length=50, verbose_name ='Фамилия')
    patronymic = models.CharField(max_length=50, verbose_name ='Отчество', **NULLABLE)
    email = models.EmailField(verbose_name='Почта')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    owner = models.ForeignKey(to=User, on_delete=models.SET_NULL, **NULLABLE,
                              related_name='clients', verbose_name='Владелец')

    def __str__(self):
        patronymic = ''
        if self.patronymic is not None:
            patronymic = self.patronymic
        return f'{self.last_name} {self.first_name} {patronymic}({self.email})'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='Тема')
    text = models.TextField(verbose_name='Текст')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создано')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Изменено')
    owner = models.ForeignKey(to=User, on_delete=models.SET_NULL, **NULLABLE,
                              related_name='messages', verbose_name='Владелец')

    def __str__(self):
        return f'{self.title} ({truncatechars(self.text, 70)})'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

class NewsLetter (models.Model):
    PEREODIC = {
        'OT': 'разовая',
        'PD': 'ежедневная',
        'PW': 'еженедельная',
        'PM': 'ежемесячная'
    }

    STATUS = {
        'ON': 'включена',
        'OFF': 'выключена',
    }

    name = models.CharField(max_length=50, verbose_name='Название')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    first_mailing_at = models.DateTimeField(verbose_name='Первая отправка')
    periodic = models.CharField(max_length=2, choices = PEREODIC, default='OT', verbose_name='Периодичность')
    status = models.CharField(max_length=3, choices= STATUS, default='OFF',  verbose_name='Статус')
    clients = models.ManyToManyField('Client', related_name='newsletters',verbose_name='Клиенты')
    message = models.ForeignKey('Message', on_delete=models.PROTECT, related_name='newsletters', verbose_name= 'Сообщение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name= 'Создана')
    owner = models.ForeignKey(to=User, on_delete=models.SET_NULL, **NULLABLE,
                                 related_name='products', verbose_name='Владелец')

    def __str__(self):
        return f'{self.name} ({self.first_mailing_at}) {self.message}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ['created_at', 'name']
        permissions = [
            ('can_change_status', 'Can change status')
        ]

    def get_history(self):
        return DjangoJobExecution.objects.filter(job_id=str(self.pk))
    # def save(self, *args,**kwargs):
    #     super(NewsLetter,self).save(*args, **kwargs)
    #     NewsAppScheduler.job_new(self)


class NewsLetterHistory (models.Model):

    newsletter = models.ForeignKey('NewsLetter', related_name='history', on_delete=models.CASCADE, verbose_name='Рассылка')
    started_at = models.DateTimeField(auto_now_add=True, verbose_name='Запущена')
    finished_at = models.DateTimeField(verbose_name='Завершена')
    is_success = models.BooleanField(verbose_name='Статус')
    comment = models.TextField(**NULLABLE, verbose_name='Ответ сервера')

    def __str__(self):
        return f'{self.newsletter} ({self.finished_at} - {self.is_success})'

    class Meta:
        verbose_name = 'История рассылок'
        verbose_name_plural = 'История рассылок'
        ordering = ['finished_at']

newsapp/forms.py
from django import forms
from django.forms import CheckboxSelectMultiple

from newsapp.models import NewsLetter, Client, Message


# class DateTimePicker(forms.DateTimeInput):
#     input_type = 'datetime-local'


class NewsLetterForm (forms.ModelForm):
    # first_mailing_at = forms.DateTimeField(label='Первая отправка')

    class Meta:
        model = NewsLetter
        exclude = ('status','owner')
        widgets = {
            'first_mailing_at': forms.DateTimeInput(format='%Y-%m-%dT%H:%M', attrs={'type': 'datetime-local'}),
            # 'first_mailing_at': DateTimePicker(),
            'clients':CheckboxSelectMultiple
        }


    def __init__(self, *args, **kwargs):
        super(NewsLetterForm, self).__init__(*args, **kwargs)
        owner = kwargs['instance'].owner
        self.fields['clients'].queryset = Client.objects.filter(owner=owner)
        self.fields['message'].queryset = Message.objects.filter(owner=owner)

newsapp/views.py
import json

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.core.serializers.json import DjangoJSONEncoder
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView

from blog.models import Blog
from newsapp.forms import NewsLetterForm
from newsapp.models import NewsLetter, Client, Message
from newsapp.src.newsapp_scheduler import NewsAppScheduler


# Рассылки ------------------------
class NewsLetterListView(LoginRequiredMixin, ListView):
    model = NewsLetter
    template_name = 'newsapp/newsletter_list.html'
    extra_context = {
        'title': 'Рассылки'
    }

    def get_queryset(self):
        if self.request.user.has_perm('newsapp.view_newsletter'):
            return NewsLetter.objects.all()

        return NewsLetter.objects.filter(owner=self.request.user)


class NewsLetterUpdateView(UserPassesTestMixin, UpdateView):
    model = NewsLetter
    form_class = NewsLetterForm
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:newsletter_list')
    extra_context = {
        'title': 'Рассылка',
        'title_card': 'Редактирование рассылки',
        'title_href': {'url': 'newsapp:newsletter_delete', 'text': 'Удалить рассылку'},
    }


    def test_func(self):
        return self.request.user.has_perm('newsapp.change_newsletter') or self.request.user == self.get_object().owner


    def form_valid(self, form):
        if form.is_valid():
            new_obj = form.save()
            new_obj.status = 'OFF'
            new_obj.save()
            NewsAppScheduler.job_new(new_obj)
            NewsAppScheduler.job_off(new_obj.pk)

        return super().form_valid(form)


class NewsLetterCreateView(LoginRequiredMixin, CreateView):
    model = NewsLetter
    form_class = NewsLetterForm
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:newsletter_list')
    extra_context = {
        'title': 'Рассылка',
        'title_card': 'Добавление рассылки',
    }


    def form_valid(self, form):
        if form.is_valid():
            new_obj = form.save()
            new_obj.owner = self.request.user
            new_obj.save()
            NewsAppScheduler.job_new(new_obj)
            NewsAppScheduler.job_off(new_obj.pk)

        return super().form_valid(form)


class NewsLetterDetailView(UserPassesTestMixin, DetailView):
    model = NewsLetter


    def test_func(self):
        return self.request.user.has_perm('newsapp.view_newsletter') or self.request.user == self.get_object().owner


class NewsLetterDeleteView(UserPassesTestMixin, DeleteView):
    model = NewsLetter
    template_name = 'newsapp/uni_delete.html'
    success_url = reverse_lazy('newsapp:newsletter_list')
    extra_context = {
        'title': 'Удаление рассылки',
        'title_card': 'рассылку',
        'title_href': {'url': 'newsapp:newsletter_edit'},
    }


    def test_func(self):
        return self.request.user.has_perm('newsapp.delete_newsletter') or self.request.user == self.get_object().owner


    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        NewsAppScheduler.job_delete(self.object.pk)
        super(NewsLetterDeleteView,self).delete(*args, **kwargs)

# Клиенты ------------------------
class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    # template_name = 'newsapp/other_list.html'
    extra_context = {
        'title': 'Клиенты',
        'title_plural': 'клиентов'
    }

    def get_queryset(self):
        if self.request.user.has_perm('newsapp.view_client'):
            return Client.objects.all()

        return Client.objects.filter(owner=self.request.user)


class ClientUpdateView(UserPassesTestMixin, UpdateView):
    model = Client
    fields = ['first_name', 'last_name', 'patronymic', 'email', 'comment']
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:client_list')
    extra_context = {
        'title': 'Клиент',
        'title_card': 'Редактирование клиента',
        'title_href': {'url': 'newsapp:client_delete', 'text': 'Удалить клиента'},
    }


    def test_func(self):
        return self.request.user.has_perm('newsapp.change_client') or self.request.user == self.get_object().owner



class ClientDeleteView(UserPassesTestMixin, DeleteView):
    model = Client
    template_name = 'newsapp/uni_delete.html'
    success_url = reverse_lazy('newsapp:client_list')
    extra_context = {
        'title': 'Удаление клиента',
        'title_card': 'клиента',
        'title_href': {'url': 'newsapp:client_edit'},
    }


    def test_func(self):
        return self.request.user.has_perm('newsapp.delete_client') or self.request.user == self.get_object().owner


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    fields = ('first_name', 'last_name', 'patronymic', 'email', 'comment')
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:client_list')
    extra_context = {
        'title': 'Клиент',
        'title_card': 'Добавление клиента',
    }

    def form_valid(self, form):
        if form.is_valid():
            client = form.save()
            client.owner = self.request.user
            client.save()
        return super().form_valid(form)

# Сообщения ------------------------
class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    extra_context = {
        'title': 'Сообщения',
        'title_plural': 'сообщений'
    }


    def get_queryset(self):
        if self.request.user.has_perm('newsapp.view_message'):
            return Message.objects.all()

        return Message.objects.filter(owner=self.request.user)


class MessageUpdateView(UserPassesTestMixin, UpdateView):
    model = Message
    fields = ('title', 'text')
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:message_list')
    extra_context = {
        'title': 'Сообщениe',
        'title_href': {'url': 'newsapp:message_delete', 'text': 'Удалить сообщениe'},
        'title_card': 'Редактирование сообщения'
    }


    def test_func(self):
        return self.request.user.has_perm('newsapp.change_message') or self.request.user == self.get_object().owner


class MessageDeleteView(UserPassesTestMixin, DeleteView):
    model = Message
    template_name = 'newsapp/uni_delete.html'
    success_url = reverse_lazy('newsapp:message_list')
    extra_context = {
        'title': 'Удаление сообщения',
        'title_card': 'сообщение',
        'title_href': {'url': 'newsapp:message_edit'},
    }

    def test_func(self):
        return self.request.user.has_perm('newsapp.delete_message') or self.request.user == self.get_object().owner


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    fields = ('title', 'text')
    template_name = 'newsapp/uni_edit.html'
    success_url = reverse_lazy('newsapp:message_list')
    extra_context = {
        'title': 'Сообщениe',
        'title_card': 'Добавление сообщения',
    }


    def form_valid(self, form):
        if form.is_valid():
            message = form.save()
            message.owner = self.request.user
            message.save()
        return super().form_valid(form)


@login_required
def change_status(request, pk):
    page = request.GET['page']
    newsletter_item = get_object_or_404(NewsLetter, pk=pk)
    if request.user.has_perm('newsapp.can_change_status') or newsletter_item.owner == request.user:
        if newsletter_item.status == 'ON':
            newsletter_item.status = 'OFF'
            NewsAppScheduler.job_off(pk)
        elif newsletter_item.status == 'OFF':
            newsletter_item.status = 'ON'
            NewsAppScheduler.job_on(pk)
        newsletter_item.save()
    if page == 'detail':
        return redirect(reverse('newsapp:newsletter_view', args=(pk,)))
    return redirect(reverse('newsapp:newsletter_list'))


def mainpage(request):

    blog_set = Blog.objects.filter(is_published=True).order_by('?')
    object_list = blog_set[:3]

    active_newsletter = NewsLetter.objects.filter(status='ON').count()
    disable_newsletter = NewsLetter.objects.filter(status='OFF').count()
    total_newsletter = NewsLetter.objects.count()

    total_clients = Client.objects.values('email').distinct().count()

    context = {
        "data_set": [disable_newsletter, active_newsletter],
        "total_newsletter": total_newsletter,
        "object_list": object_list,
        "total_clients": total_clients
    }
    return render(request, 'newsapp/index.html', context)

newsapp/templates/newsapp/index.html
{% extends 'base.html' %}

{% block content %}
{% load blog_tags %}
{% load newsapp_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Главная страница {{ title }}</h1>
            <div class="row m-1 row-cols-2">
                <div class="col-lg-6">
                    <div class="card mb-4 h-100">
                        <div class="card-header">
                            <i class="fas fa-chart-pie me-1"></i>
                            Анализ рассылок
                        </div>
                        <div class="card-body">
                            <canvas id="myPieChart" width="100%" height="50"></canvas>
                        </div>
                        <div class="card-footer">Общее количество рассылок: {{ total_newsletter }}</div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <div class="card mb-4 h-100">
                        <div class="card-header">
                            <i class="fas fa-chart-area me-1"></i>
                            Приток клиентов
                        </div>
                        <div class="card-body">
                            <canvas id="myAreaChart" width="100%" height="40"></canvas>
                        </div>
                        <p class="m-3">

                        </p>
                        <div class="card-footer">В нашей базе клиентов: {{ total_clients }} </div>
                    </div>
                </div>
            </div>
            <div class="row m-1 row-cols-3">
                {% for object in object_list %}
                <div class="card rounded-3 shadow-sm">
                    <div class="card-header w-100">
                        <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                    </div>
                    <div class="card-body">
                        <p>
                            {% if object.image %}
                            <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                            {% endif %}
                        </p>
                        <p>
                            {{ object.short_content }}
                        </p>
                    </div>
                    <div class="card-footer">
                        <a type="button" href="{% url 'blog:blog_detail' object.slug  %}"
                           class="m-1 w-100 btn btn-lg btn-secondary">Подробнее</a>
                        {% if user.is_content_manager or blog.owner == user %}
                        <a type="button" href="{% url 'blog:blog_update' object.slug %}"
                           class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </main>
    {% include 'footer.html' %}

</div>

{% endblock content %}

newsapp/templates/newsapp/newsletter_detail.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="d-flex justify-content-between">
                            <span>
<!--                            <i class="fas fa-table me-1"></i>-->
                            <h4 class="card-title">{{object.name}}</h4>
                            </span>
                                {% if object.owner == user or perms.newsapp.change_newsletter %}
                                   <a href="{% url 'newsapp:newsletter_edit' object.pk %}"
                                       class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                                        <i class="text-end bi bi-person-plus"></i>
                                        Редактировать рассылку
                                    </a>
                                 {% endif %}
                           </div>
                            <div class="text-muted">Создана {{object.created_at}}</div>
                        </div>
                        <div class="card-body">
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                    <b class="text-muted">Первая отправка: </b>
                                    {{object.first_mailing_at}}
                                </li>
                                <li class="list-group-item">
                                    <b class="text-muted">Периодичность: </b>
                                    {{object.get_periodic_display}}
                                </li>
                                <li class="list-group-item">
                                    <b class="text-muted">Статус: </b>
                                    {% if object.status == 'ON' %}
                                    <a href="{% url 'newsapp:status' object.pk %}?page=detail" class="link-success"
                                       data-bs-toggle="tooltip" title="Выключить рассылку">
                                        {{object.get_status_display}}
                                    </a>
                                    {% elif object.status == 'OFF' %}
                                    <a href="{% url 'newsapp:status' object.pk %}?page=detail" class="link-danger"
                                       data-bs-toggle="tooltip" title="Включить рассылку">
                                        {{object.get_status_display}}
                                    </a>
                                    {% else %}
                                    {{object.get_status_display}}
                                    {% endif %}
                                </li>
                                <li class="list-group-item">
                                    <b class="text-muted">Сообщение: </b>
                                    {% if object.owner == user or perms.newsapp.change_message %}
                                    <a href="{% url 'newsapp:message_edit' object.message.pk %}" class="link-dark"
                                       data-bs-toggle="tooltip" title="Редактировать сообщение">
                                        {{object.message.title}}
                                    </a>
                                    {% else %}
                                    {{object.message.title}}
                                    {% endif %}
                                    <p><small>{{object.message.text}}</small></p>
                                </li>
                                <li class="list-group-item">
                                    <b class="text-muted">Комментарий: </b>
                                    {{object.comment}}
                                </li>
                                <li class="list-group-item">
                                    <b class="text-muted">История: </b>
                                    <table id="datatablesSimple">
                                        <thead>
                                        <tr>
                                            <th>Начата</th>
                                            <th>Длительность</th>
                                            <th>Статус</th>
                                            <th>Ответ сервера</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for item in object.get_history %}
                                        <tr>
                                            <td>{{item.run_time}}</td>
                                            <td>{{item.duration}}</td>
                                            <td>
                                                {% if item.status == 'Error!' %}
                                                <div class="text-danger">Ошибка</div>
                                                {% elif item.status == 'Executed'%}
                                                Завершена
                                                {% else %}
                                                Выполняется
                                                {% endif %}
                                            </td>
                                            <td>{{item.exception}}</td>
                                        </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                </li>
                            </ul>
                            <!--                            <a href="#" class="btn btn-outline-primary">Перейти куда-нибудь</a>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

newsapp/templates/newsapp/newsletter_list.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    Список рассылок
                    </span>
                    <a href="{% url 'newsapp:newsletter_new' %}" class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        <i class="text-end bi bi-person-plus"></i>
                        Добавить рассылку
                    </a>
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                        <tr>
                            <th>Имя</th>
                            <th>Первая отправка</th>
                            <th>Периодичность</th>
                            <th>Статус</th>
                            <th>Сообщение</th>
                            <th>Комментарий</th>
                            {% if perms.newsapp.view_newsletter %}
                            <th>Владелец</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя</th>
                            <th>Первая отправка</th>
                            <th>Периодичность</th>
                            <th>Статус</th>
                            <th>Сообщение</th>
                            <th>Комментарий</th>
                            {% if perms.newsapp.view_newsletter %}
                            <th>Владелец</th>
                            {% endif %}
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'newsapp:newsletter_view' object.pk %}"
                                   data-bs-toggle="tooltip" title="Редактировать рассылку">{{object.name}}</a>
                            </td>
                            <td>{{object.first_mailing_at}}</td>
                            <td class="center">{{object.get_periodic_display}}</td>
                            <td class="center">
                                {% if object.status == 'ON' %}
                                    <a href="{% url 'newsapp:status' object.pk %}?page=list" class="link-success"
                                    data-bs-toggle="tooltip" title="Выключить рассылку">
                                    {{object.get_status_display}}
                                    </a>
                                {% elif object.status == 'OFF' %}
                                    <a href="{% url 'newsapp:status' object.pk %}?page=list" class="link-danger"
                                    data-bs-toggle="tooltip" title="Включить рассылку">
                                    {{object.get_status_display}}
                                    </a>
                                {% else %}
                                    {{object.get_status_display}}
                                {% endif %}
                            </td>
                            <td>{{object.message|truncatechars:30}}</td>
                            <td>{{object.comment|truncatechars:80}}</td>
                            {% if perms.newsapp.view_newsletter %}
                            <td>{{object.owner}}</td>
                            {% endif %}
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
{% include 'footer.html' %}

</div>
{% endblock content %}

newsapp/templates/newsapp/other_list.html
{% extends 'base.html' %}

{% block content %}
{% load newsapp_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header">
                    <i class="fas fa-table me-1"></i>
                    Список {{ title_plural }}
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                        <tr>
                            {% if object_list|is_list_not_empty %}
                            {% for name in object_list.1|verbose_names %}
                            <th>{{name}}</th>
                            {% endfor %}
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for object in object_list %}
                        <tr>
                            <td><a href="{% url 'newsapp:newsletter_view' object.pk %}">{{object.name}}</a></td>

                            <td>{{object.comment}}</td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}