blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

appname = BlogConfig.name

urlpatterns = [
   path ('blog/', cache_page(60)(BlogListView.as_view()),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
   path('delete_blog/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
import random

from django.db import models
from django.template.defaultfilters import truncatechars
from pytils.translit import slugify

from users.models import User, NULLABLE


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    slug = models.CharField(max_length=100, unique=True, verbose_name='Slug')
    image = models.ImageField(upload_to='products/', blank=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    update_at = models.DateTimeField(auto_now=True, verbose_name='Изменен')
    is_published = models.BooleanField(default=False, verbose_name='Признак публикации')
    views_counter = models.IntegerField(default=0, verbose_name='Количество просмотров')
    content = models.TextField(verbose_name='Содержимое')
    owner = models.ForeignKey(to=User, on_delete=models.SET_NULL, **NULLABLE,
                                 related_name='blogs', verbose_name='Владелец')

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'
        ordering = ['-created_at']
        permissions = [
            ('can_publish_article' , 'Can publish article')
        ]

    def __str__(self):
        return f'{self.title}'

    @property
    def short_content(self):
        return truncatechars(self.content, 100)

    def save(self, *args, **kwargs):
        if not self.pk:
            self.slug = slugify(self.title)
        super(Blog,self).save(*args, **kwargs)

blog/forms.py
from django import forms

from blog.models import Blog

class BlogForm(forms.ModelForm):

    class Meta:
        model = Blog
        fields = ['title', 'content', 'image', 'is_published']


class BlogContentForm(BlogForm):

    def __init__(self, *args, **kwargs):
        super(BlogContentForm, self).__init__(*args, **kwargs)
        self.fields['title'].disabled = True
        self.fields['content'].disabled = True
        self.fields['image'].disabled = True

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from blog.forms import BlogForm, BlogContentForm
from blog.models import Blog



class BlogListView(ListView):
    model = Blog
    extra_context = {
        'title': 'Блог',
        'title_plural': 'статей'
    }

    def get_queryset(self):
        return Blog.objects.filter(is_published=True)


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['title', 'content', 'image', 'is_published']
    # template_name = 'blog/blog_form.html'
    extra_context = {
        'title': 'Блог',
        'title_card': 'Добавление статьи',
    }
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            blog = form.save()
            blog.owner = self.request.user
            blog.save()
        return super().form_valid(form)

class BlogUpdateView(UserPassesTestMixin, UpdateView):
    model = Blog
    form_class = BlogForm
    # template_name = 'blog/blog_form.html'
    extra_context = {
        'title': 'Блог',
        'title_card': 'Редактирование статьи',
        'title_href': {'url': 'blog:blog_delete', 'text': 'Удалить статью'},
    }
    success_url = reverse_lazy('blog:blog_list')

    def get_form_class(self):
        if self.request.user.has_perm('blog.change_blog') or self.object.owner == self.request.user:
            return BlogForm

        return BlogContentForm


    def test_func(self):
        return (self.request.user.has_perm('blog.change_blog') or
                self.request.user == self.get_object().owner or
                self.request.user.is_content_manager)


    def get_success_url(self):
        return reverse('blog:blog_detail', args=(self.kwargs['slug'],))


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        # obj = get_object_or_404(Blog.objects,slug=self.kwargs[self.slug_url_kwarg])
        self.object = super().get_object(queryset)
        self.object.views_counter += 1
        self.object.save()

        return self.object

class BlogDeleteView(UserPassesTestMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')
    extra_context = {
        'title': 'Удаление статьи',
        'title_card': 'статьи',
        'title_href': {'url': 'blog:blog_update'},
    }

    def test_func(self):
        return self.request.user.has_perm('blog.delete_blog') or self.request.user == self.get_object().owner

blog/templates/blog/blog_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
{% load newsapp_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    Вы действительно хотите удалить {{ title_card }}?
                    </span>
                </div>
                <div class="card-body">
                    <p>
                    <h4>
                        {{object}}
                    </h4>
                    </p>
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>
                            <button type="submit" class="gy-2 w-100 btn btn-lg btn-outline-danger">Удалить</button>
                        </p>
                        <p>
                            <a href="{% url title_href.url object.slug %}"
                               class="gy-2 w-100 btn btn-lg btn-outline-primary">Отменить</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

blog/templates/blog/blog_detail.html
{% extends 'base.html' %}

{% block content %}
{% load blog_tags %}
<div id="layoutSidenav_content">

    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>
            <div class="row">
                <div class="col-12">
                    <div class="card rounded-3 shadow-sm m-1 col">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                        </div>
                        <div class="card-body">
                            {% if object.image %}
                            <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                            {% endif %}
                            <p>
                                {{ object.content }}
                            </p>
                            <p class="text-secondary"><small>
                                Просмотров {{ object.views_counter }}
                            </small></p>

                        </div>
                        <div class="card-footer">
                            {% if perms.blog.change_blog or object.owner == user or user.is_content_manager %}
                            <a type="button" href="{% url 'blog:blog_update' object.slug %}"
                               class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

blog/templates/blog/blog_form.html
{% extends 'base.html' %}

{% block content %}
{% load newsapp_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    {{ title_card }}
                    </span>
                    {% if title_href.text %}
                    <span>
                    <a href="{% url title_href.url object.slug %}" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        <i class="text-end bi bi-person-plus"></i>
                        {{ title_href.text }}
                    </a>
                    </span>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <p><label class="col-sm-2 col-form-label align-top" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                        <div class="text-danger">{{ f.errors }}</div>
                        {% endfor %}
                        <p>
                            <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

blog/templates/blog/blog_list.html
{% extends 'base.html' %}

{% block content %}
{% load blog_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    Список {{ title_plural }}
                    </span>
                    <a href="{% url 'blog:blog_create' %}"
                       class="link-primary link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        <i class="text-end bi bi-person-plus"></i>
                        Добавить статью
                    </a>
                </div>
                <div>
                <div class="row m-1 row-cols-1 row-cols-md-3">
                    {% for object in object_list %}
                    <div class="card rounded-3 shadow-sm">
                        <div class="card-header w-100">
                            <h4 class="my-0 fw-normal">{{ object.title }}</h4>
                        </div>
                        <div class="card-body">
                            <p>
                                {% if object.image %}
                                <img class="card-img-left img-thumbnail" src="{{ object.image|add_media }}">
                                {% endif %}
                            </p>
                            <p>
                                {{ object.short_content }}
                            </p>
                        </div>
                        <div class="card-footer">
                            <a type="button" href="{% url 'blog:blog_detail' object.slug  %}"
                               class="m-1 w-100 btn btn-lg btn-secondary">Подробнее</a>
                            {% if perms.blog.change_blog or object.owner == user or user.is_content_manager %}
                            <a type="button" href="{% url 'blog:blog_update' object.slug %}"
                               class="m-1 w-100 btn btn-lg btn-primary">Редактировать</a>
                            {% endif %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

blog/templates/blog/editor.html
{% extends 'base.html' %}

{% block content %}
{% load newsapp_tags %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    {{ title_card }}
                    </span>
                    {% if title_href.text %}
                    <span>
                    <a href="{% url title_href.url object.pk %}" class="link-danger link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover">
                        <i class="text-end bi bi-person-plus"></i>
                        {{ title_href.text }}
                    </a>
                    </span>
                    {% endif %}
                </div>
                <div class="card-body">
                    <form action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <p><label class="col-sm-2 col-form-label align-top" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
                        <div class="text-danger">{{ f.errors }}</div>
                        {% endfor %}
                        <p>
                            <button type="submit" class="w-100 btn btn-lg btn-outline-primary">Сохранить</button>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}