blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

appname = BlogConfig.name

urlpatterns = [
   path ('blog/', cache_page(60)(BlogListView.as_view()),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
   path('delete_blog/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UserConfig
from users.views import LoginView, ProfileUpdateView, UserCreateView, confirm_user, change_status, UserListView

appname = UserConfig.name

urlpatterns = [
   path ('login/', LoginView.as_view(), name='login'),
   path ('logout/', LogoutView.as_view(), name='logout'),
   path('profile/', ProfileUpdateView.as_view(), name='profile'),
   path('register/', UserCreateView.as_view(), name='register'),
   path('user_list/', UserListView.as_view(), name='user_list'),
   path('confirm/<str:token>', confirm_user, name='confirm'),
   path('user_status/<int:pk>', change_status, name='user_status'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import random, string


NULLABLE = {'null':True, 'blank':True}

class User (AbstractUser):

    avatar = models.ImageField(upload_to='users/', **NULLABLE, verbose_name='аватар')
    phone = models.CharField(max_length=30, **NULLABLE, verbose_name='телефон')
    token = models.CharField(max_length=100, **NULLABLE, verbose_name='токен')

    class Meta:
        permissions = [
            ('can_change_status', 'Can change status')
        ]

    @staticmethod
    def generate_password(length: int):
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for _ in range(length))

        return password


    @property
    def is_content_manager(self):
        return self.has_perm('blog.can_publish_article')

users/forms.py
from cProfile import label

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField


class LoginUserForm(AuthenticationForm):
    username = UsernameField(label= 'Логин', widget=forms.TextInput(attrs={"autofocus": True}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class ProfileUpdateForm(forms.ModelForm):

    username = forms.CharField(label= 'Логин', disabled=True)
    email = forms.EmailField(disabled=True)

    class Meta:
        model = get_user_model()
        fields =('username', 'email', 'first_name', 'last_name', 'phone', 'avatar')


class CreateUserForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields =('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

users/views.py
import secrets
from pyexpat.errors import messages

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.hashers import make_password
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import UpdateView, CreateView, ListView

from newsapp.src.utils import sendmail
from users.forms import ProfileUpdateForm, CreateUserForm, LoginUserForm
from users.models import User


class LoginView(BaseLoginView):
    form_class = LoginUserForm
    template_name = 'users/user_form.html'
    extra_context = {
        'title_form': 'Вход на сайт'
    }

    def form_valid(self, form):
        return super().form_valid(form)

    def form_invalid(self, form):
        if 'recovery' in form.data:
            email = form.data.get('username')
            user = User.objects.filter(email=email).first()
            if user is not None:
                password = user.generate_password(8)
                user.password = make_password(password)
                user.save()
                sendmail(
                    [user.email],
                    'Восстановление пароля',
                    f'Ваш новый пароль {password}')
                messages.success(self.request, 'На вашу по4ту отправлен пароль')
                return redirect(reverse('users:login'))
            else:
                messages.warning(self.request, f'Пользователя {email} не существует')
        return super().form_invalid(form)


class UserListView(PermissionRequiredMixin, ListView):
    model = get_user_model()
    extra_context = {
        'title': 'Пользователи'
    }
    permission_required = 'users.view_user'

class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model =  get_user_model()
    form_class = ProfileUpdateForm
    template_name = 'users/user_form.html'
    extra_context = {
        'title_form': 'Профиль пользователя'
    }

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self):
        return self.request.user

class UserCreateView(CreateView):
    model = get_user_model()
    form_class = CreateUserForm
    template_name = 'users/user_form.html'
    extra_context = {
        'title_form': 'Регистрация пользователя',
        'create_user': True
    }
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        token = secrets.token_hex(16)
        user.is_active = False
        user.token = token
        user.save()
        sendmail(
            [user.email],
            'Подтверждение регистрации',
        'Пожалуйста подтвердите свой адрес электронной почты для завершения регистрации\n'+
        f'http://{self.request.get_host()}/confirm/{token}')

        return super().form_valid(form)


def confirm_user(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()

    return redirect(reverse('users:login'))

@permission_required('users.can_change_status', raise_exception=True)
def change_status(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    elif not user.is_active == 'OFF':
        user.is_active = True
    user.save()
    return redirect(reverse('users:user_list'))

users/templates/users/user_form.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">

    <main class="row overflow-auto">
        <div class="d-flex justify-content-center">
            <div class="card rounded-3 shadow-sm m-1 col-5">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">Введите информацию о пользователе</h4>
                </div>
                <form method="post" action="" enctype="multipart/form-data">
                    <div class="card-body">
                        {% csrf_token %}
                        <div class="form-error">{{ form.non_field_errors }}</div>
                        {% for f in form %}
                        <p>
                            <label class="col-sm-2 col-form-label align-top" for="{{ f.id_for_label }}">
                                {{ f.label }}</label>
                            {{ f }}
                        </p>
                        <div class="form-error">{{ f.errors }}</div>
                        {% endfor %}
                    </div>
                    <div class="card-footer">
                        {% if user.is_authenticated %}
                        <button type="submit" class="my-2 w-100 btn btn-lg btn-primary">Сохранить</button>
                        {% else %}
                        {% if create_user %}
                        <button type="submit" class="my-2 w-100 btn btn-lg btn-primary">Зарегистрировать</button>
                        {% else %}
                        <button type="submit" class="my-2 w-100 btn btn-lg btn-primary" name="login">Войти</button>
                        <button type="submit" class="my-2 w-100 btn btn-secondary" name="recovery">
                            Восстановить пароль
                        </button>
                        {% endif %}
                        {% endif %}
                        {% if footer_url %}
                        <a type="button" href="{% url footer_url object.pk %}"
                           class="my-2 w-100 btn btn-lg btn-secondary">Удалить</a>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}

</div>
{% endblock content %}

users/templates/users/user_list.html
{% extends 'base.html' %}

{% block content %}
<div id="layoutSidenav_content">
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">{{ title }}</h1>

            <div class="card mb-4">
                <div class="card-header d-flex justify-content-between">
                    <span>
                    <i class="fas fa-table me-1"></i>
                    Список пользователей
                    </span>
                </div>
                <div class="card-body">
                    <table id="datatablesSimple">
                        <thead>
                        <tr>
                            <th>Ник</th>
                            <th>ФИО</th>
                            <th>Почта</th>
                            <th>Статус</th>
                            <th>Последний вход</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Ник</th>
                            <th>ФИО</th>
                            <th>Почта</th>
                            <th>Статус</th>
                            <th>Последний вход</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for object in object_list %}
                        {% if not object.is_superuser %}
                        <tr>
                            <td class="center">{{object.username}}</td>
                            <td class="center">{{object.last_name}} {{object.first_name}}</td>
                            <td class="center">{{object.email}}</td>
                            <td class="center">
                                {% if object.is_active %}
                                    <a href="{% url 'users:user_status' object.pk %}" class="link-success"
                                    data-bs-toggle="tooltip" title="Заблокировать пользователя">
                                    активен
                                    </a>
                                {% elif not object.is_active %}
                                    <a href="{% url 'users:user_status' object.pk %}" class="link-danger"
                                    data-bs-toggle="tooltip" title="Разблокировать пользователя">
                                    заблокирован
                                    </a>
                                {% else %}
                                    {{object.is_active}}
                                {% endif %}
                            </td>
                            <td>{{object.last_login}}</td>
                        </tr>
                        {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </main>
{% include 'footer.html' %}

</div>
{% endblock content %}