blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogCreateView, BlogUpdateView, BlogDetailView, BlogDeleteView

appname = BlogConfig.name

urlpatterns = [
   path ('blog/', cache_page(60)(BlogListView.as_view()),name='blog_list'),
   path('new_blog/', BlogCreateView.as_view(), name='blog_create'),
   path('edit_blog/<slug:slug>', BlogUpdateView.as_view(), name='blog_update'),
   path('view_blog/<slug:slug>', cache_page(60)(BlogDetailView.as_view()), name='blog_detail'),
   path('delete_blog/<slug:slug>', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('newsapp.urls', namespace='newsapp')),
    path('', include(('blog.urls','blog'), namespace='blog')),
    path('', include(('users.urls', 'users'), namespace='users')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsapp/urls.py
from django.urls import path

from newsapp.apps import NewsappConfig
from newsapp.views import NewsLetterListView, NewsLetterDetailView, change_status, ClientListView, MessageListView, \
    ClientUpdateView, MessageUpdateView, ClientCreateView, NewsLetterCreateView, MessageCreateView, \
    NewsLetterUpdateView, MessageDeleteView, NewsLetterDeleteView, ClientDeleteView, mainpage

app_name = NewsappConfig.name

urlpatterns = [
    path('', mainpage, name='home'),
    path('newsletter_list', NewsLetterListView.as_view(), name='newsletter_list'),
    path('newsletter_view/<int:pk>', NewsLetterDetailView.as_view(), name='newsletter_view'),
    path('newsletter_edit/<int:pk>', NewsLetterUpdateView.as_view(), name='newsletter_edit'),
    path('newsletter_delete/<int:pk>', NewsLetterDeleteView.as_view(), name='newsletter_delete'),
    path('newsletter_new/', NewsLetterCreateView.as_view(), name='newsletter_new'),
    path('status/<int:pk>', change_status, name='status'),
    path('client_list', ClientListView.as_view(), name='client_list'),
    path('client_edit/<int:pk>', ClientUpdateView.as_view(), name='client_edit'),
    path('client_delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('client_new/', ClientCreateView.as_view(), name='client_new'),
    path('message_list', MessageListView.as_view(), name='message_list'),
    path('message_edit/<int:pk>', MessageUpdateView.as_view(), name='message_edit'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('message_new/', MessageCreateView.as_view(), name='message_new'),

]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UserConfig
from users.views import LoginView, ProfileUpdateView, UserCreateView, confirm_user, change_status, UserListView

appname = UserConfig.name

urlpatterns = [
   path ('login/', LoginView.as_view(), name='login'),
   path ('logout/', LogoutView.as_view(), name='logout'),
   path('profile/', ProfileUpdateView.as_view(), name='profile'),
   path('register/', UserCreateView.as_view(), name='register'),
   path('user_list/', UserListView.as_view(), name='user_list'),
   path('confirm/<str:token>', confirm_user, name='confirm'),
   path('user_status/<int:pk>', change_status, name='user_status'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load blog_tags %}
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link rel="icon" href="{% static 'newsapp/chat-chat-svgrepo-com.svg' %}">
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"/>
    <link href="{% static 'newsapp/css/styles.css' %}" rel="stylesheet"/>
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'newsapp:home' %}">Менеджер рассылок</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
        <!--        <div class="input-group">-->
        <!--            <input class="form-control" type="text" placeholder="Поиск ..." aria-label="Поиск ..."-->
        <!--                   aria-describedby="btnNavbarSearch"/>-->
        <!--            <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>-->
        <!--        </div>-->
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown"
               aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                <!--                <li><a class="dropdown-item" href="#!">Activity Log</a></li>-->
                <li>
                    <hr class="dropdown-divider"/>
                </li>
                <li>
                <li>
                    <form method="post" action="{% url 'users:logout' %}">
                        {% csrf_token %}
                        <button class="dropdown-item" type="submit">Выйти</button>
                    </form>
                </li>
                {% else %}
                <li><a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a></li>
                <!--                <li><a class="dropdown-item" href="#!">Activity Log</a></li>-->
                <li>
                    <hr class="dropdown-divider"/>
                </li>
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
                {% endif %}
            </ul>
        </li>
    </ul>
</nav>
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
            <div class="sb-sidenav-menu">
                <div class="nav">
                    <div class="sb-sidenav-menu-heading">Меню</div>
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'newsapp:newsletter_list' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                        Рассылки
                    </a>
                    <a class="nav-link" href="{% url 'newsapp:client_list' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                        Клиенты
                    </a>
                    <a class="nav-link" href="{% url 'newsapp:message_list' %}">
                        <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                        Сообщения
                    </a>
                    {% if perms.users.view_user %}
                    <a class="nav-link" href="{% url 'users:user_list' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-users"></i></div>
                        Пользователи
                    </a>
                    {% endif %}
                    {% endif %}
                    <a class="nav-link" href="{% url 'blog:blog_list' %}">
                        <div class="sb-nav-link-icon"><i class="fa-solid fa-blog"></i></div>
                        Блог
                    </a>
                </div>
            </div>
            <div class="sb-sidenav-footer">
                {% if user.is_authenticated %}
                <div class="small">Вы зашли как:</div>
                <img src="{{ user.avatar|add_media }}" alt="" width="32" height="32" class="rounded-circle me-2">
                {{user.username}}
                {% endif %}
            </div>
        </nav>
    </div>

    {% block content %}
    {% endblock content %}

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src={% static "newsapp/js/scripts.js" %}></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js"
        crossorigin="anonymous"></script>
<script src={% static "newsapp/js/datatables-simple-demo.js" %}></script>

<script>
    let DataSet = {{ data_set|escapejs }};
</script>
<script src={% static "newsapp/assets/demo/chart-pie-demo.js" %}></script>
<script src={% static "newsapp/assets/demo/chart-area-demo.js" %}></script>
</body>
</html>

templates/footer.html
    <footer class="py-4 bg-light mt-auto">
        <div class="container-fluid px-4">
            <div class="d-flex align-items-center justify-content-between small">
                <div class="text-muted">Copyright &copy; Danver, the Last Dinosaur 2024</div>
                <div>
                    <a href="https://ru.wikipedia.org/wiki/I2P">Privacy Policy</a>
                    &middot;
                    <a href="https://ru.wikipedia.org/wiki/%D0%A7%D0%B5%D0%BB%D0%BE%D0%B2%D0%B5%D0%BA%D0%B0%D0%B9%D0%BF%D0%B0%D0%B4%D0%BE%D0%BD%D0%BE%D0%B6%D0%BA%D0%B0">Terms &amp; Conditions</a>
                </div>
            </div>
        </div>
    </footer>